### ISSUE TITLE
How use this code on practice?

### ISSUE THREAD

**Issue by SweetBaget** [18vijayb/TwitchChatVideoRenderer#1]
Sorry for that question. Just i'm noob and don;t understand how to use your code on specified clip or vod or chat file

**Comment by 18vijayb** [comment]
You need to download a chat file as a json file through TCD. The file must go through ChatJsonRefine and TwitchChatGenerator. I'm still working on this repo and will let you know once it is complete

**Comment by SweetBaget** [comment]
> You need to download a chat file as a json file through TCD. The file must go through ChatJsonRefine and TwitchChatGenerator. I'm still working on this repo and will let you know once it is complete

Okay, i'll be waiting :)

**Comment by SweetBaget** [comment]
> You need to download a chat file as a json file through TCD. The file must go through ChatJsonRefine and TwitchChatGenerator. I'm still working on this repo and will let you know once it is complete

I'm finally reached the second file. And here i need your help: what's mean 'overlayInterval', 'startTime', and 'index'. What i need to write? Thanks you for you code and future answer ;)

**Comment by 18vijayb** [comment]
Use createChatImageFaster. For the overlayInterval, pass in something like this
{
      "interval": [
        {startTime},
        {endTime}
      ],
      "chatCoordinates": {
        "widthScale": 0.3,
        "heightScale": 0.8
      },
      "backgroundRGBA": "rgba(150,150,150,0.7)",
      "textRGB": "rgb(255,255,255)",
      "reference": {}
    }

index can be any number, startTime will be the startTime of the chat interval.

**Comment by SweetBaget** [comment]
> Use createChatImageFaster. For the overlayInterval, pass in something like this
> {
> "interval": [
> {startTime},
> {endTime}
> ],
> "chatCoordinates": {
> "widthScale": 0.3,
> "heightScale": 0.8
> },
> "backgroundRGBA": "rgba(150,150,150,0.7)",
> "textRGB": "rgb(255,255,255)",
> "reference": {}
> }
> 
> index can be any number, startTime will be the startTime of the chat interval.

Thanks you a lot. I'm finally did my first chat replay
